void timer_init();
void timer_expired();
void change_minutes(bool up, bool alarm);
void change_hours(bool up, bool alarm);
void write_time();
void write_alarm();
void write_time_hours();
void write_time_minutes();
void write_alarm_hours();
void write_alarm_minutes();
